commenting out filesystem cleanup

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -30,19 +30,19 @@ for i in "${container_id[@]}"; do
 done
 
 # Cleanup Filesystem
-echo; echo ">>>>>> Cleaning filesystem"
-clean_filesystem=( ${PROMETHEUS_ROOT} ${ALERTMANAGER_ROOT} ${GRAFANA_ROOT} )
-for i in "${clean_filesystem[@]}"; do
-  if [[ -d ${i} ]]; then
-    rm -rf ${i}
-    if [[ $? -eq 0 ]]; then
-      echo "Deleted folder ${i}"
-    elif [[ $? -ne 0 ]]; then
-      echo "Could not delete folder ${i}. Error code was $?"
-      exit 1
-    fi
-  fi
-done
-rm -rf ${DOCKER_VOLUME}/docker-compose.yml
+# echo; echo ">>>>>> Cleaning filesystem"
+# clean_filesystem=( ${PROMETHEUS_ROOT} ${ALERTMANAGER_ROOT} ${GRAFANA_ROOT} )
+# for i in "${clean_filesystem[@]}"; do
+#   if [[ -d ${i} ]]; then
+#     rm -rf ${i}
+#     if [[ $? -eq 0 ]]; then
+#       echo "Deleted folder ${i}"
+#     elif [[ $? -ne 0 ]]; then
+#       echo "Could not delete folder ${i}. Error code was $?"
+#       exit 1
+#     fi
+#   fi
+# done
+# rm -rf ${DOCKER_VOLUME}/docker-compose.yml
 # Finish
 echo; echo ">>>>>> Uninstall complete"
